global:
  scrape_interval: 5s
scrape_configs:

- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 192.168.2.100:9090

- job_name: aula
  static_configs:
  - targets:
    - 192.168.2.14:3030

- job_name: windows
  static_configs:
  - targets:
    - 192.168.2.6:9182

- job_name: teste-http-python
  static_configs:
  - targets:
    - 192.168.2.100:5001

- job_name: teste-flask_my-app
  static_configs:
  - targets:
    - 192.168.2.100:5005

- job_name: node-exporter
  static_configs:
  - targets:
    - 192.168.2.100:9100

- job_name: cadvisor
  static_configs:
  - targets:
    - 192.168.2.100:8080

- job_name: blackbox
  static_configs:
  - targets:
    - 192.168.2.100:9115

- job_name: blackbox-dns
  metrics_path: /probe
  params:
    module: 
    - dns_google
  static_configs:
  - targets:
    - "8.8.8.8"

- job_name: blackbox-tcp
  metrics_path: /probe
  params:
    module: 
    - tcp_connect
  static_configs:
  - targets:
    - "192.168.2.100:5005"

- job_name: natura-status
  metrics_path: /probe
  params:
    module: 
    - http_natura
  static_configs:
  - targets:
    - "https://www.natura.com.br"
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 192.168.2.100:9115  

- job_name: mysql-exporter
  static_configs:
  - targets:
    - 192.168.2.100:9104     

- job_name: push-gateway
  honor_labels: True
  static_configs:
  - targets:
    - 192.168.2.100:9091      

- job_name: grafana
  static_configs:
  - targets:
    - 192.168.2.100:3000

- job_name: sql-server
  static_configs:
  - targets:
    - 192.168.2.100:4000