services:
  jenkins:
    build: .
    #image: jenkins/jenkins:lts
    ports:
      - "8084:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
  ssh-agent:
    image: jenkins/ssh-agent
volumes:
  jenkins_home: